config/routes.rb
Rails.application.routes.draw do
  resources :oscillators
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/oscillator.rb
class Oscillator < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/oscillators_controller.rb
class OscillatorsController < ApplicationController
  before_action :set_oscillator, only: [:show, :edit, :update, :destroy]

  # GET /oscillators
  # GET /oscillators.json
  def index
    @oscillators = Oscillator.all
  end

  # GET /oscillators/1
  # GET /oscillators/1.json
  def show
  end

  # GET /oscillators/new
  def new
    @oscillator = Oscillator.new
  end

  # GET /oscillators/1/edit
  def edit
  end

  # POST /oscillators
  # POST /oscillators.json
  def create
    @oscillator = Oscillator.new(oscillator_params)

    respond_to do |format|
      if @oscillator.save
        format.html { redirect_to @oscillator, notice: 'Oscillator was successfully created.' }
        format.json { render :show, status: :created, location: @oscillator }
      else
        format.html { render :new }
        format.json { render json: @oscillator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oscillators/1
  # PATCH/PUT /oscillators/1.json
  def update
    respond_to do |format|
      if @oscillator.update(oscillator_params)
        format.html { redirect_to @oscillator, notice: 'Oscillator was successfully updated.' }
        format.json { render :show, status: :ok, location: @oscillator }
      else
        format.html { render :edit }
        format.json { render json: @oscillator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oscillators/1
  # DELETE /oscillators/1.json
  def destroy
    @oscillator.destroy
    respond_to do |format|
      format.html { redirect_to oscillators_url, notice: 'Oscillator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oscillator
      @oscillator = Oscillator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oscillator_params
      params.require(:oscillator).permit(:frequency, :wave, :detune)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oscillators_helper.rb
module OscillatorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hseadc2017Thereminvox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'thereminvox' %>

    <%= javascript_pack_tag 'synth' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/oscillators/_form.html.erb
<%= form_with(model: oscillator, local: true) do |form| %>
  <% if oscillator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oscillator.errors.count, "error") %> prohibited this oscillator from being saved:</h2>

      <ul>
        <% oscillator.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :frequency %>
    <%= form.number_field :frequency %>
  </div>

  <div class="field">
    <%= form.label :wave %>
    <%= form.text_field :wave %>
  </div>

  <div class="field">
    <%= form.label :detune %>
    <%= form.number_field :detune %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/oscillators/edit.html.erb
<h1>Editing Oscillator</h1>

<%= render 'form', oscillator: @oscillator %>

<%= link_to 'Show', @oscillator %> |
<%= link_to 'Back', oscillators_path %>

app/views/oscillators/index.html.erb
<%
  props = {
    wet: 0.8,
    distortion: 50,
    oversample: '2x'
  }
%>

<div id="data" data-props="<%= props.to_json %>"></div>

<!-- <input id="chord-1" value="1" type="radio" name="chord" />
<input id="chord-2" value="2" type="radio" name="chord" />
<input id="chord-3" value="3" type="radio" name="chord" />
<input id="chord-4" value="4" type="radio" name="chord" />
<input id="chord-5" value="5" type="radio" name="chord" />
<ul>
  <li><label for="chord-1">1</label></li>
  <li><label for="chord-2">2</label></li>
  <li><label for="chord-3">3</label></li>
  <li><label for="chord-4">4</label></li>
  <li><label for="chord-5">5</label></li>
</ul> -->

app/views/oscillators/new.html.erb
<h1>New Oscillator</h1>

<%= render 'form', oscillator: @oscillator %>

<%= link_to 'Back', oscillators_path %>

app/views/oscillators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Frequency:</strong>
  <%= @oscillator.frequency %>
</p>

<p>
  <strong>Wave:</strong>
  <%= @oscillator.wave %>
</p>

<p>
  <strong>Detune:</strong>
  <%= @oscillator.detune %>
</p>

<%= link_to 'Edit', edit_oscillator_path(@oscillator) %> |
<%= link_to 'Back', oscillators_path %>